IsTakipSistemiMvc2/Controllers/LoguotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsTakipSistemiMvc2.Controllers
{
    public class LoguotController : Controller
    {
        // GET: Loguot
        public ActionResult Index()
        {
            Session.Abandon();
            return RedirectToAction("Index","Login");
        }
    }
}

IsTakipSistemiMvc2/Controllers/PersonelController.cs
using IsTakipSistemiMvc2.Filters;
using IsTakipSistemiMvc2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsTakipSistemiMvc2.Controllers
{

    public class PersonelController : Controller
    {
        IsTakipDataBaseEntities entity = new IsTakipDataBaseEntities();

        // GET: Personel
        [AuthFilter(3)]
        public ActionResult Index()
        {
            var personeller = (from p in entity.Personeller where p.personelYetkiTurId != 3 &&p.aktiflik==true select p).ToList();
            return View(personeller);
        }
        [AuthFilter(3)]
        public ActionResult Olustur()
        {
            BirimYetkiTurler by = birimYetkiTurlerDondor();

            ViewBag.mesaj = null;
            return View(by);
        }
        [HttpPost, ActFilter("Yeni Personel Eklendi")]
        public ActionResult Olustur(FormCollection fc)
        {
            string personelKullaniciAd = fc["kullaniciAd"];
            var personel = (from p in entity.Personeller where p.personelKullaniciAdi == personelKullaniciAd select p).FirstOrDefault();
            int birimId = Convert.ToInt32(fc["birim"]);
            if (Convert.ToInt32(fc["yetkiTur"])==1)
            {
                var birimYoneticiKontrol=(from p in entity.Personeller where p.personelBirimId == birimId && p.personelYetkiTurId == 1 select p).FirstOrDefault();

                if (birimYoneticiKontrol!=null)
                {
                    BirimYetkiTurler by = birimYetkiTurlerDondor();

                    ViewBag.mesaj = "Bu birimin Sadece 1 yoneticisi olabilir";
                    TempData["bilgi"] = null;
                    return View(by);
                }
            }
            if (personel == null)
            {
                Personeller yeniPersonel = new Personeller();
                yeniPersonel.personelAdSoyad = fc["adSoyad"];
                yeniPersonel.personelKullaniciAdi = personelKullaniciAd;
                yeniPersonel.personelParola = fc["parola"];
                yeniPersonel.personelBirimId = Convert.ToInt32(fc["birim"]);
                yeniPersonel.personelYetkiTurId = Convert.ToInt32(fc["yetkiTur"]);
                yeniPersonel.yeniPersoneller = true;
                yeniPersonel.aktiflik=true;
                entity.Personeller.Add(yeniPersonel);
                entity.SaveChanges();

                TempData["bilgi"] = yeniPersonel.personelKullaniciAdi;
                return RedirectToAction("Index");

            }
            else
            {
                BirimYetkiTurler by = birimYetkiTurlerDondor();
                ViewBag.mesaj = "Kullanici Adi Bulunmaktadir";
                TempData["bilgi"] = null;
                return View(by);
            }
        }
        [AuthFilter(3)]
        public ActionResult Guncelle(int id)
        {
            var personel = (from p in entity.Personeller where p.personelId == id select p).FirstOrDefault();
            return View(personel);
        }
        [HttpPost, ActFilter("Personel Guncellendi")]
        public ActionResult Guncelle(int id, string adSoyad)
        {
            Personeller personel = (from p in entity.Personeller where p.personelId == id select p).FirstOrDefault();

            personel.personelAdSoyad = adSoyad;
            entity.SaveChanges();
            TempData["bilgi"] = personel.personelKullaniciAdi;
            return RedirectToAction("Index");
        }
        [AuthFilter(3)]
        public ActionResult Sil(int id)
        {
            var personel = (from p in entity.Personeller where p.personelId == id select p).FirstOrDefault();
            return View(personel);
        }
        [HttpPost, ActFilter("Personel Silindi")]
        public ActionResult Sil(FormCollection fc)
        {
            int personelId = Convert.ToInt32(fc["personelId"]);
            var personel = (from p in entity.Personeller where p.personelId == personelId select p).FirstOrDefault();
            personel.aktiflik = false;
            entity.SaveChanges();
            TempData["bilgi"] = personel.personelKullaniciAdi;
            return RedirectToAction("Index");
        }

        public BirimYetkiTurler birimYetkiTurlerDondor()
        {
            BirimYetkiTurler by = new BirimYetkiTurler();
            by.birimlerList = (from b in entity.Birimler where b.aktiflik == true select b).ToList();
            by.yetkiTurlerList = (from y in entity.YetkiTurler where y.yetkiTurId != 3 select y).ToList();
            return by;
        }
    }

}

IsTakipSistemiMvc2/Controllers/SifreKontrolController.cs
using IsTakipSistemiMvc2.Filters;
using IsTakipSistemiMvc2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IsTakipSistemiMvc2.Controllers
{
    public class SifreKontrolController : Controller
    {
        IsTakipDataBaseEntities entity= new IsTakipDataBaseEntities();
        // GET: SifreKontrol
        public ActionResult Index()
        {
            int personelId = Convert.ToInt32(Session["PersonelId"]);
            if (personelId == 0) return RedirectToAction("Index","Login");
            var personel=(from p in entity.Personeller where p.personelId == personelId select p).FirstOrDefault();
            ViewBag.mesaj = null;
            ViewBag.yetkiTurId = null;
            ViewBag.sitil = null;
            return View(personel);
        }
        [HttpPost, ActFilter("Parola Degistirildi")]
        public ActionResult Index(int personelId, string eskiParola ,string yeniParola ,string yeniParolaKontrol) 
        {
            var personel = (from p in entity.Personeller where p.personelId == personelId select p).FirstOrDefault();
            if (eskiParola!=personel.personelParola)
            {
                ViewBag.mesaj = "Eski Parolanizi Yanlis Girdiniz";
                ViewBag.Sitil = "alert alert-danger";
                return View(personel);
            }
            if (yeniParola!=yeniParolaKontrol)
            {
                ViewBag.mesaj = "Yeni Parola Ve Yeni Parola Tekrari Eslesmedi";
                ViewBag.Sitil = "alert alert-danger";
                return View(personel);
            }
            if (yeniParola.Length<6 || yeniParola.Length>15)
            {
                ViewBag.mesaj = "Yeni Parola En Az 6 Karakter En Cok 15 Karakter Olmalidir";
                ViewBag.Sitil = "alert alert-danger";
                return View(personel);
            }
            personel.personelParola = yeniParola;
            personel.yeniPersoneller=false;
            entity.SaveChanges();
            TempData["bilgi"] = personel.personelKullaniciAdi;
            ViewBag.mesaj = "Parolaniz Basariyla Degistirildi Ana Sayfaya Yonlendiriliyorsunuz";
            ViewBag.sitil = "alert alert-success";
            ViewBag.yetkiTurId=personel.personelYetkiTurId;
            return View(personel);
        }
    }
}

IsTakipSistemiMvc2/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

IsTakipSistemiMvc2/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager mt-5">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active page-item"><span class="page-link">@i</span></li>
            }
            else
            {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

IsTakipSistemiMvc2/Views/Shared/_LayoutCalisan.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Is Takip Admin Calisan</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Is Takip Calisan</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Calisan", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Tamamla", "Yap", "Calisan", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("iş Takip", "Takip", "Calisan", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <div class="d-flex nav-item">
                    @Html.ActionLink("Parola Degistir", "Index", "SifreKontrol", new { }, new { @class = "btn btn-light mx-2" })
                    @Html.ActionLink("Cikis", "Index", "Loguot", new { }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

IsTakipSistemiMvc2/Views/Shared/_LayoutSistemYoneticisi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Is Takip Admin Sistem Yonetici</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery-3.7.0.min.js"></script>
    <script src="~/Scripts/gridmvc.js"></script>
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Is Takip Sistem Yonetici</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "SistemYonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Birim Islemleri", "Birim", "SistemYonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Personel Islemleri", "Index", "Personel", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Log Islemleri", "Loglar", "SistemYonetici", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <div class="d-flex nav-item">
                    @Html.ActionLink("Cikis", "Index", "Loguot", new { }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

IsTakipSistemiMvc2/Views/Shared/_LayoutYonetici.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Is Takip Admin Yonetici</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Is Takip Yonetici</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Ata", "Ata", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("iş Takip", "Takip", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <div class="d-flex nav-item">
                    @Html.ActionLink("Parola Degistir", "Index", "SifreKontrol", new { }, new {@class="btn btn-light mx-2"})
                    @Html.ActionLink("Cikis", "Index", "Loguot", new {}, new {@class="btn btn-danger"})
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

IsTakipSistemiMvc2/Views/Shared/_PartialAylarSelect.cshtml
<select name="aylar" id="aylar" class="form-select">
    <option value="01">Ocak</option>
    <option value="02">Subat</option>
    <option value="03">Mart</option>
    <option value="04">Nisan</option>
    <option value="05">Mayis</option>
    <option value="06">Haziran</option>
    <option value="07">Temmuz</option>
    <option value="08">Agustos</option>
    <option value="09">Eylul</option>
    <option value="10">Ekim</option>
    <option value="11">Kasim</option>
    <option value="12">Aralik</option>
</select>