IsTakipSistemiMvc2/Models/Loglar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int loId { get; set; }
        public string logAciklama { get; set; }
        public string actionAd { get; set; }
        public string controllerA { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> personelId { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}

IsTakipSistemiMvc2/Controllers/SistemYoneticiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IsTakipSistemiMvc2.Models;
using System.Globalization;
using IsTakipSistemiMvc2.Filters;

namespace IsTakipSistemiMvc2.Controllers
{
    public class SistemYoneticiController : Controller
    {
        IsTakipDataBaseEntities entity = new IsTakipDataBaseEntities();
        // GET: SistemYonetici
        [AuthFilter(3)]
        public ActionResult Index()
        {
            var birimler = (from b in entity.Birimler where b.aktiflik == true select b).ToList();
            string labelBirim = "[";
            foreach (var birim in birimler)
            {
                labelBirim += "'" + birim.birimAd + "',";
            }
            labelBirim += "]";
            ViewBag.labelBirim = labelBirim;

            List<int> islerToplam = new List<int>();
            foreach (var birim in birimler)
            {
                int toplam = 0;
                var personeller=(from p in entity.Personeller where p.personelBirimId==birim.birimId && p.aktiflik==true select p).ToList();
                foreach (var personel in personeller)
                {
                    var isler=(from i in entity.Isler where i.isPersonelId==personel.personelId select i).ToList();
                    toplam += islerToplam.Count();
                }
                islerToplam.Add(toplam);
            }

            string dataIs = "[";
            foreach (var i in islerToplam)
            {
                dataIs += "'" + i + "',";
            }
            dataIs += "]";
            ViewBag.dataIs = dataIs;
            return View();
        }

        public ActionResult Birim()
        {
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);
            if (yetkiTurId == 3)
            {
                var birimler = (from b in entity.Birimler where b.aktiflik == true select b).ToList();
                return View(birimler);

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public ActionResult Olustur()
        {
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);
            if (yetkiTurId == 3)
            {

                return View();

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost, ActFilter("Yeni Birim Eklendi")]
        public ActionResult Olustur(string birimAd)
        {
            Birimler yeniBirim = new Birimler();
            string yeniAd = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(birimAd);
            yeniBirim.birimAd = yeniAd;
            yeniBirim.aktiflik = true;
            entity.Birimler.Add(yeniBirim);
            entity.SaveChanges();

            TempData["bilgi"] = yeniBirim.birimAd;
            return RedirectToAction("Birim");
        }
        public ActionResult Guncelle(int id)
        {
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);
            if (yetkiTurId == 3)
            {
                var birim = (from b in entity.Birimler where b.birimId == id select b).FirstOrDefault();

                return View(birim);

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost, ActFilter("Birim Guncellendi")]

        public ActionResult Guncelle(FormCollection fc)
        {
            int birimId = Convert.ToInt32(fc["birimId"]);
            string yeniAd = fc["birimAd"];

            var birim = (from b in entity.Birimler where b.birimId == birimId select b).FirstOrDefault();
            birim.birimAd = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(yeniAd);
            entity.SaveChanges();
            TempData["bilgi"] = birim.birimAd;

            return RedirectToAction("Birim");
        }
        [ActFilter("Bir Birim Silindi")]
        public ActionResult Sil(int id)
        {
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);
            if (yetkiTurId == 3)
            {
                var birim = (from b in entity.Birimler where b.birimId == id select b).FirstOrDefault();
                birim.aktiflik = false;
                entity.SaveChanges();
                TempData["bilgi"] = birim.birimAd;
                return RedirectToAction("Birim");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [AuthFilter(3)]
        public ActionResult Loglar()
        {
            var loglar = (from l in entity.Loglar orderby l.tarih descending select l).ToList();
            return View(loglar);
        }
    }
}

IsTakipSistemiMvc2/Views/SistemYonetici/Birim.cshtml
@model IEnumerable<IsTakipSistemiMvc2.Models.Birimler>
@{
    ViewBag.Title = "Birim";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}
<p class="mt-5">
    @Html.ActionLink("Yeni Birim Ekle", "Olustur", new { }, new {@class="btn btn-primary"})
</p>
<table class="table table-bordered table-striped table-dark">
    <tr class="text-center">
        <th>
            @Html.DisplayNameFor(model=>model.birimAd)
        </th>
        <th>

        </th>
        <th>

        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>
                @Html.DisplayFor(modelItem => item.birimAd)
            </td>
            <td>
                @Html.ActionLink("Guncelle", "Guncelle", new { id = item.birimId }, new { @class = "btn btn-success" })
            </td>
            <td>
                @Html.ActionLink("Sil", "Sil", new { id = item.birimId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>

IsTakipSistemiMvc2/Views/SistemYonetici/Guncelle.cshtml
@model IsTakipSistemiMvc2.Models.Birimler
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}
<div class="container mt-5">
    <h3>Birim Guncelleme</h3>
    <hr />
    @using (Html.BeginForm("Guncelle", "SistemYonetici", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.birimId)
        <div class="row mb-3">
            @Html.LabelFor(model => model.birimAd, htmlAttributes: new { @class = "col-sm3 col-form-label" })
            <div class="col-sm-6">
                @Html.EditorFor(model => model.birimAd, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="text-center d-grid gap-5 col-6 mx-auto">
            <button class="btn btn-success" type="submit">Guncelle</button>
        </div>
    }
</div>

IsTakipSistemiMvc2/Views/SistemYonetici/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}

<h2>Index</h2>
<script src="~/Scripts/chart.min.js"></script>
<div class="mt-5">
    <canvas id="myChart" width="10" height="5"></canvas>
</div>
<script>
    const ctx = document.getElementById('myChart').getContext('2d');
    const mychart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(ViewBag.labelBirim),
            datasets: [{
                label: 'Birimlerin Toplam Isleri',
                data: @Html.Raw(ViewBag.dataIs),
                backgroundColor: ['#22333b'],
                borderColor: ['#0a0900'],
                borderWidth:2}]
        }
    })
</script>

IsTakipSistemiMvc2/Views/SistemYonetici/Loglar.cshtml
@model IEnumerable<IsTakipSistemiMvc2.Models.Loglar>
    @using GridMvc.Html
@{
    ViewBag.Title = "Loglar";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}
<div class="container mt-5">
    @Html.Grid(Model).Columns(column =>
{
    column.Add(m => m.Personeller.personelAdSoyad).Titled("Personel Ad Soyad").Filterable(true);
    column.Add(m => m.logAciklama).Titled("Aciklama");
    column.Add(m => m.actionAd).Titled("Action Adi");
    column.Add(m => m.controllerA).Titled("Controller Adi");
    column.Add(m => m.tarih).Titled("Tarih").Sortable(true);

}).WithPaging(3)
</div>

IsTakipSistemiMvc2/Views/SistemYonetici/Olustur.cshtml
@{
    ViewBag.Title = "Olustur";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}
<div class="container mt-5">
    <h3>Yeni Birim Ekleme Islemi</h3>
    <hr />
    @using(Html.BeginForm("Olustur", "SistemYonetici", FormMethod.Post))
    {
                <div class="row mb-3">
                    <label for="birimAd" class="col-sm-3 col-form-label">Birim Adi:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="birimAd" name="birimAd" />
                    </div>
                </div>
                <div class="text-center d-grid gap-5 col-6 mx-auto">
                    <button class="btn btn-primary" type="submit">Ekle</button>
                </div>
            }
</div>